# Copyright 2023-2025 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "creek-jekyll-theme", "~> 1.0"

# # If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-include_snippet', "~> 0.2"
end
