# A Workflow for triggering a new release.
#
# Releasing is a two stage process.
# 1. Running this workflow will check the build is green and then push a release tag to the repo, e.g. v1.2.3
# 2. Pushing the release tag (e.g. v1.2.3) will trigger the main CI build.yml.
#    This main build has conditional steps that only run, or only don't run, when building a release build, i.e. a build triggered when a release tag is pushed.

name: Release

on: [workflow_dispatch]

permissions:
  contents: read

concurrency: "${{ github.repository }}-versioning"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
      - name: Fetch version history
        run: git fetch --tags --unshallow
      - name: Set up JDK
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2.7.0
        with:
          gradle-home-cache-cleanup: true
      - name: Ensure build is green
        run: ./gradlew build
      - name: Release
        run: |
          # The following command will trigger the build.yml workflow as it pushes a release tag
          ./gradlew release
      - name: Capture version info
        run: |
          echo "Release version: $(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_STEP_SUMMARY 

